name: snapeat1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  provider: ^6.0.4
  carousel_slider: ^4.2.1
  flutter_switch: ^0.3.2
  intl: ^0.18.0
  intl_phone_field: ^3.1.0
  google_maps_flutter: ^2.2.3
  flutter_google_places: ^0.3.0
  geolocator: ^9.0.2
  location: ^4.4.0
  flutter_geocoder: ^0.2.2-nullsafety
  map_launcher: ^2.4.0
  custom_info_window: ^1.0.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  credit_card_scanner: ^1.0.5
  country_list_pick: ^1.0.1+6
  google_fonts: ^3.0.1
  simple_gradient_text: ^1.2.4
  flutter_staggered_grid_view: ^0.6.2
  flash: ^2.0.5
  telephony: ^0.2.0
  pin_code_fields: ^7.4.0
  table_calendar: ^3.0.9
  image_fade: ^0.6.2
  animate_gradient: ^0.0.2
  animated_text_kit: ^4.2.2
  fluttertoast: ^8.2.1
  # flutter_multi_carousel: ^1.0.3





  







dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
     - assets/images/
     - assets/icons/
     - assets/intro_images/
     
# IBMPlexSans fonts
  # fonts:
  #   - family: IBMPlexSans
  #     fonts:
  #       - asset: assets/fonts/IBMPlexSans-Regular.ttf


        
  
       
