// ignore_for_file: constant_identifier_names, file_names
// All images url Here....

const introback = "assets/icons/Group 19630.svg";
const IMAGE186 = "assets/intro_images/intro2 (7).png"; //Intro screen1
const IMAGE103 = "assets/intro_images/intro1 (1).png"; // Intro screen1
const IMAGE1052 = "assets/intro_images/intro2 (1).png"; // Intro screen2
const IMAGE105 = "assets/intro_images/intro1.png"; // Intro screen2
const IMAGE1054 = "assets/intro_images/intro1 (2).png"; // Intro screen2
const HOME_COOCKED_IMAGE = "assets/intro_images/intro home cooked.png"; // Intro Screen 3
const INTRO_CHIEF = "assets/intro_images/intr0.png"; // intro screen 3

const IMAGE_106 = "assets/intro_images/image 106 (1).png"; // Intro screen 4
const IMAGE_891 = "assets/images/Frame_891__1_-removebg-preview.png"; // Intro screen 4
const IMAGE3710084 = "assets/intro_images/intro2 (4).png"; // intro screen 5
const FRAME_900 = "assets/intro_images/Group 21328.png"; // intro screen 6
const HONOUR_HOLDING_IMAGE = "assets/intro_images/intro2 (6).png"; // intro scree 7
const IMAGE_101 = "assets/intro_images/intro6.png"; // intro sceen 8
const IMAGE_99 = "assets/intro_images/intro7.png"; // Intro screen 9
const filterIcon = "assets/icons/Settings, Filter.svg"; // home screen
const HAND_ICON = "ssets/images/pin (1).png"; // restaurants screen
const LOCATION_PIN = "assets/images/pin (2).png"; // restaurants screen
const locationIcon = "assets/icons/location.svg"; // Location&timeScreen
const HomeIcon2 = "assets/icons/home (1).svg"; // Location&timeScreen
const thinkIcon = "assets/icons/thinkIcon.svg"; //Location&timeScreen
const bagIcon = "assets/icons/Group 18764.svg";
const eatIcon = "assets/icons/Group 18799.svg";
const splashLogo = "assets/images/splashlogo.png"; // splash screen
const thumbIcon = "assets/images/hand.png";
const menuIcon = "assets/images/Vector (3).png"; // profile Screen
const dropPin = "assets/images/pin.png"; // All Lcation Screeen
const userImage = "assets/images/Ellipse 123.png";
const restaurantsImage = "assets/images/image 76.png"; //  ShowRestaurantsMarkerOnMapView Screen
const arrowIcon = "assets/icons/arrowIcon.svg"; //  ShowRestaurantsMarkerOnMapView Screen
const offerIcon = "assets/images/offer.png"; //  ShowRestaurantsMarkerOnMapView Screen
const offericon2 = "assets/icons/Vector (3).svg"; // home screen
const userimage1 = "assets/images/Avator.png"; // profile screen
const doller = "assets/images/dollar 2.png"; // profile menu  screen
const sitaraIcon = "assets/images/Group 743.png"; // profile menu screen
const flag = "assets/images/united-kingdom.png"; // profile menu screen
const favoriteIcon = "assets/images/Heart, Favorite.1.png"; // home Screen
const favoriteIcon1 = "assets/images/Vector.png"; // home Screen
const eyeIconOff = "assets/icons/Group.svg";
const eyeIcon = "assets/icons/eyeIcon1.svg";
const spleshbackground = "assets/images/6.png";
const splashImage = "assets/images/Group 21255.png";
const bakgroundimage = "assets/images/bakground.png";
const backButton = "assets/images/Group.png";
const icon3d = "assets/icons/View 3D.svg";
const icon3D = "assets/images/Group 19048.png";
const red3d = "assets/icons/3d.svg";
const picIcon = "assets/icons/Group.svg";
const manyPerson = "assets/images/Group 704.png";
const dateicon = "assets/images/Group.png";
const notification = "assets/icons/nottification.svg";
const SettinIcon = "assets/icons/settinsIcon.svg";
const mapviewIcon1 = "assets/icons/Map.svg";
const searchIcon = "assets/icons/Search, Loupe.svg";
const starIcon = "assets/icons/Solid.svg";
const NextIcon = "assets/icons/Frame 906.svg";
const backIcon = "assets/images/Group 19630.png";
const bikeIcon = "assets/icons/Group 18755.svg";
const victoryIcon = "assets/images/trophy 3.png";
const chiefAtHomeIcon = "assets/icons/vector5.svg";
const bacgroundImage = "assets/images/8705 3.png"; // my rewars Screen
const CircleImage = "assets/images/Group 796.png";
const diamond = "assets/images/Group 536.png";
const creditRedim = "assets/images/credit.png";
const endIcon = "assets/icons/Group 19660.svg";
const nftImage = "assets/images/nft (1) 2 (1).png";
const binance = "assets/images/image 188.png";
// all intro images....
const image203 = "assets/images/image 203.png";
const IntroBottomclrImage = "assets/images/Vector (8).png";
const intro_image1 = "assets/images/intro1.png";
const intro_image2 = "assets/images/intro2.png";
const intro_image3 = "assets/images/intro3.png";
const intro_image6 = "assets/images/intro6.png";
const intro_image8 = "assets/images/intro8.png";
const IntroBottomclrImagered = "assets/images/Vector (9).png";
const ScroolingImage14 = "assets/images/Analytics.png";

// bottonav All Images here..
const cameraIcon = "assets/icons/LOGO.svg";
const QrScanIcon = "assets/images/qr.png";
const HomeIcon = "assets/icons/Home.svg";
const FileIcon = "assets/icons/file.svg";
const LeaderBordeIcon = "assets/icons/Leaderboard.svg";
const ProfileIcon = "assets/icons/Profile.svg";
const asapIcon = "assets/icons/asaptimer.svg";
const sedulecallendor = "assets/icons/seduleCallender.svg";
const sliverM = "assets/images/Silver 1.png";
const goldenM = "assets/images/Golden 3.png";
const silverModel = "assets/images/silvermodel.png";
const branzM = "assets/images/Bronze 1.png";
const branzMoedal = "assets/images/bronzMedal.png";
const goldenModal = "assets/images/Golden M.png";
const camrealogo = "assets/images/LOGO.png";
const rIcon = "assets/images/rlogo.png"; // profile menu Screen
const cIcon = "assets/icons/c.svg"; // profile menu Screen
const rewardImage = "assets/images/Group 21271.png"; // profile menu Screen
const doller2 = "assets/images/dollar 1.png"; // How to earn rewards Dialogbox
const nfty = "assets/images/nft (1) 1.png"; // How to earn rewards Dialogbox
const re1 = "assets/images/Group 19511.png"; // How to earn rewards Dialogbox
const re2 = "assets/images/Group 19511.png"; // How to earn rewards Dialogbox
const starIcon2 = "assets/images/Vector (2).png"; // How to earn rewards Dialogbox
const instagramIcon = "assets/images/instagram 1.png"; // My details Screen
const applePayImage = "assets/images/image 109.png"; // wallet Screen
const creditcardgreenImage = "assets/images/credit1.png"; // wallet Screen
const creditcardgtredImage = "assets/images/credit2.png"; // wallet Screen
const lockicon = "assets/images/lock 1.png"; // wallet Screen
const debitIcon = "assets/images/debit.png"; //wallet Screen
const offerImage = "assets/images/Group 19524.png"; // my rewards Screen
const checkIcon = "assets/images/Group 18829.png"; // Profile Menu // Message Screen
const pin = "assets/images/pin (1).png"; // restaurants creen
const STEP_ICON = "assets/images/step.png"; // rewards credit screen
