// ignore_for_file: constant_identifier_names, file_names

// All Texts Here....
const SNAPEAT_CLIENT = 'SnapEat Client'; // main dart screen app title
const resendOtpTimermsg = "You can try again in a few more seconds."; // otp verify screen
const GET_30_REWARDSTXT = "Get £30 reward credits and 30 NFTs when you sign up with an invite code.*"; // otp verify + enter mobile screen
const ENTER_YOUR_MOBILE_NUMBER = "Enter your mobile number"; // enter mobile screen
const HAVE_DISCOUNT_CODE = "Have a discount code?"; // otp verify + enter mobile screen
const buttontext = "Confirm"; //
const VERIY_YOUR_MOBILE_NUMBER = "Verify your mobile number"; //  otp verify screen
const WE_HAVE_SENT_MAGIC_TEXT = "We’ve sent a magic code to your phone."; //  otp verify screen
const ALL_RIGHT_RESERVED = " 2023 Snap Eat Ltd, All rights reserved"; // terms conditions screen
const search = "Search for Restaurants & more";
const distance = "Distance"; // filter screen
const hygiene = "Hygiene rating"; // filter screen
const time = "Time"; // filter screen
const price = "Price"; // filter screen
const toprated = "Top Rated"; // filter screen
const PickedForYou = "Picked for you (Recommended)";
const Establishment_type = "Establishment type";
const apply_filter = "Apply Filter"; // filter  data screen
const other_filter = "Other filters"; // filter data screen
const view_all = "View All"; // filter  data Restaurants  screen
const menu_abailable = "3D menu available"; // filter data screen
const full_picture = "Full picture menu"; // filter data screen
const top_eat_only = "TopEats only"; // filter data screen
const open_now = "Open Now"; // filter data screen
const contact_less = "Contactless ordering"; // filter data screen
const star_review = "5 star reviews on covid safety "; // filter data screen
const michelin_star_only = "Michelin Star Only"; // filter data screen
const ATMOSPHERE = "Atmosphere"; // atomsphere screen
const reservation_availability_text = "Reservation availability"; // Reservation  availability screen
const does_not_require_reservation = "Does not require reservation deposit"; // Reservation  availability screen
const EnterEmail = "Enter your email address"; // enter email screen
const start_snap_eating = "Start SnapEating"; // terms conditions screen
const enter_discount = "Enter discount code"; // enter mobile screen
const restaurants = "Restaurants"; // home Screen
const home_cooked = "HomeCooked"; // home Screen + filter data Screen
const new_order = "New orders"; // my order Screen
const past_order = "Past orders"; // my order Screen
const dishes = "Dishes"; // my favourites screen
const delivery = "Delivery"; // loation Time screen
const eatout = "Eat out"; // loation Time screen
const collection = "Collection"; // loation Time screen
const chief_atHome = "ChefAtHome"; // loation Time screen
const upload_food = "Upload \nFoodSnap"; // service popup buttom sheet screen
const explore3d = "Explore \n3D Food"; // service popup buttom sheet screen
const choose_service = "Choose  \n a service"; // service popup buttom sheet screenconst choose_service =
const ChooseService = "Choose a service"; // service popup buttom sheet screen
const qrScan = "QR Scan"; // service popup buttom sheet screen
const ASAP = "ASAP"; // service popup buttom sheet screen
const forLater = "For later"; // service popup buttom sheet screen
const Deliverytime = "Delivery time";
const seduleforLater = "Schedule for later"; // // Schedule buttom sheet screen
const Confirm = "Confirm"; // dilivery time  buttom sheet screen
const Today = "Today"; // ScheduleForLater screen
const Tomorrow = "Tomorrow"; // ScheduleForLater screen
const LocatioAndTime = "Location & Time"; // location time screen
const newAddress = "Enter new address"; //
const pinOnMap = "Pin on map"; // location and time screen
const dropPinToExactLocation = "Drop pin to exactlocation";
const addNewAddress = "Add new Address"; // add new address screen
const building_name = "Flat or House number / Building name"; // add new address screen
const Streetname = "Street address"; // add new address screen
const PostCode = "Post code"; // add new address screen
const searchforReataurants = "Search for restaurants, cuisines & dishes";
const Leaderboard = "Leaderboard"; // leaderboardScreen
const Thisleaderboard_is = "This leaderboard is "; // leaderboardScreen
const MyOrder = "My orders"; // My order screen
const message = " Messages"; // Profile menu Screen
const profile = "Profile"; // Profile menu Screen
const promotions = "Promotions"; // Profile menu Screen
const Favorites = "My Favorites"; // Profile menu Screen
const Contributions = "My Contributions"; // Profile menu Screen
const myReawards = "My Rewards"; // Profile menu Screen
const Contact = "Contact us"; // Profile menu Screen
const About = "About"; // Profile menu Screen
const every_order_helps_wants_to_see = "Every order helps. Want to see how?"; // Profile menu Screen
const invite_a_friend_get_rewards = "Invite a friend & Get £10 reward credit"; // Profile menu Screen
const rate_app_get_reward_credit = "Rate App & Get £5 reward credit"; // Profile menu Screen
const become_homechief = "Become a SnapEat HomeChef"; // profie  menu Screen
// const become_snapEat_driver = "Become a SnapEat driver"; // profie  menu Screen
const all_right_reserved_sanpeat_ltd = "2023 Snap Eat Ltd, All rights reserved."; // profie  menu Screen
const snapeat_registered_trademark = "SnapEat is a registered trademark in the UKIPO & EUIPO"; // profie  menu Screen
const Language = "Language"; // profie  menu Screen
const help_community = """Help the SnapEater community,
     earn points and rewards.
     This is how:"""; // How To earn dialogbox on
const bloggerTxt =
    "Did you know that we also every_order_helps_wants_to_see restaurants to find food bloggers for collabs, invites and special promos. If you are a blogger, let us know. Food blogger status is subject to review and depends on your account’s engagement rate. Don’t forget to share & tag us, so we notice you. "; // on  My Details Screen
const redeemtext =
    "*Since most NFTs are Ethereum-based tokens, your gift card currency will be Ethereum (ETH). We will convert the NFT coins that you have earned to ETH using the exchange rate as of the time they are earned.You can request an email with detailed transactions here."; // reward Screen
const CorporateCards = "Gift & Corporate cards";
const see_it_before_you_eat_it = "See it before you eat it   "; // splash  Screen
const SNAP = "Snap"; // splash  Screen
const EAT = "Eat"; // splash  Screen
const LOREM_IPSUM = "Lorem ipsum"; // intro text and images list screen
const SKIP = "Skip"; // intro screen main page
const VERIFY = "Verify"; // otp verify screen
const REDEEMABLE_ON_FIRST = "*Redeemable on first order. See "; //  otp verify screen
const Enter_otp_field = "Please enter otp field";
const T_AND_C = "T&Cs"; //  otp verify screen
const FOR_FULL_DETAIL = " for full details."; //  otp verify screen
const ENTER_VALID_NUMBER = "Enter a valid number."; // enter mobile screen
const PLEASE_ENTER_FULL_NUMBER = "Please enter your number.";
const WHATS_YOUR_EMAIL_ADDRESS = "What's your email address?"; // enter email screen
const PLEASE_ENTER_EMAIL = "Please enter email."; // enter email screen
const PLEASE_ENTER_VALID_EMAIL = "Please enter a valid email."; // enter email screen
const WELCOME_TO_THE = "Welcome to the"; // terms conditions screen
const SNAPEAT = "SnapEat"; // terms conditions screen
const COMMUNITY = " community!"; // terms conditions screen
const BY_SIGNING_YOU = 'By signing up you agree to '; // terms conditions screen
const TERMS_OF_USE = "Terms of Use "; // terms conditions screen
const AND = 'and '; // terms conditions screen
const PRIVACY_POLICY = "Privacy Policy"; // terms conditions screen
const CURRENT_LOCATION_ASP = "Current Location - ASP"; // Restaurants screen
const BROUSE = "Browse"; // Restaurants screen
const BY_CUSINE = "by cusine"; // Restaurants screen
const POPULAR_RESTAURANTS = "Popular Restaurants"; // Restaurants screen
const RECOMMENDED_DISHES = "Recommended Dishes"; // Restaurants screen
const VIEW_ALL = "View All"; // Restaurants screen
const RESTAURANTS_LIST = "Restaurants List"; // Restaurants screen
const MAP_VIEW = "Map View"; // Restaurants screen
const ORDER_AGAIN = "Order again"; // Restaurants screen
const SCAN_YOUR_CARD = "Scan your card"; // add payment method screen
const DEBIT_CREDIT_CARD = "Debit or credit card"; // add payment method screen
const APPLE_PAY = "Apple Pay"; // add payment method screen
const POST_CODE = "Post code"; // add payment method screen
const CVV = "CVV"; // add payment method screen
const MMYY = "MM/YY"; // add payment method screen
const EXPIRY = "Expiry"; // add payment method screen
const CARD_NUMBER = "Card Number"; // add payment method screen
const NEW_PAYMENT_METHOD = "New payment method"; // add payment method screen
const T123 = "123"; // add payment method screen
const SE186ZF = "SE18 6ZF"; // add payment method screen
const YOUR_PAYMENT_INFORMATION = "Your payment information is stored securely"; // add payment method screen
const SAVE = "Save"; // add payment method screen
const DECEMBER12 = "12th-Dec-2022"; // reservation availability screen
const REVIEW_SCORE = "Review score"; // Review score screen
const PRICE = "Price"; // Review score screen
const HYGIENE_RATING = "Hygiene rating"; // Review score screen
const DELIVERY_FEE = "Delivery fee"; // Review score screen
const MIN_ORDER_VALUE = "Min order value for delivery"; // Review score screen
const FILTERS = "Filters"; // filter data main page screen
const RESET_FILTERS = "Reset filters"; // filter data main page screen
const SERVICES = "Services"; // filter data main page screen
const RESULT_50 = " (50 results)"; // filter data main page screen
const SORT_BY = "Sort by"; // filter data main page screen
const CUISINE = "Cuisines"; // filter data main page screen
const DIETRY = "Dietary"; // filter data main page screen
const DISCOUNTS = "Discounts"; // filter data main page screen
const AT_HOME = "At Home"; // add new address  screen
const AT_WORK = "At Work"; // add new address  screen
const AT_OWN_TAG = "Add own tag"; // add new address  screen
const ANY_INTRUCTIONS_IE = "Any instructions i.e. parking, entrance location, entry code?"; // add new address  screen
const CURRENT_LOCATION = "Current Location"; // Location & time screen
const SOHO_LONDON = "Soho London"; // Location & time screen
const LAST_MONTH = "Last Month"; // LeaderBoardScreen
const THIS_MONTH = 'This Month'; // LeaderBoardScreen
const MONTH_12 = '12 Month'; // LeaderBoardScreen
const THANKS_FOR_HELPING_SNAPEATRS = "Thank you for helping the SnapEaters community."; // ThisMonthClass
const GET_50REWARDS_TOP_SNAPEATRS = "🏆£50 reward for Top SnapEaters of the month."; // ThisMonthClass
const GET_100REWARDS_TOP_SNAPEATRS = "🏆£100 reward for Top SnapEater of the year"; // ThisMonthClass
const LIVE = "LIVE"; // ThisMonthClass
const CLOSED = "CLOSED"; // ThisMonthClass
const NEW_ORDERS = "New orders"; // my order class
const PAST_ORDERS = "Past orders"; // my order class
const DILIVERED = "Dilivered"; // my order class
const TRACK_PROGRESS = "Track progress"; // my order class
const YOU_HAVE_REWARDS_CREDIT_NFT = "You have reward credits NFT credits"; // profile menu main page screen
const SNAP_FOODIE = "SnapFoodie"; // profile menu main page screen
const EARN_MORE_1500_POINTS_TO_UNLOCK_REWARDS = "Earn 1,500 more points to unlock SnapEpicure level."; // profile menu main page screen
const HOW_TO_EARN_POINTS_REWARDS = "How to earn points & rewards?"; // profile menu main page screen
const YOUR_FOOD_SNAPS = "Your FoodSnaps"; // contributions screen
const MEAL_REVIEWS = "Meal Reviews"; // contributions screen
const RESTAURANTS_REVIEWS = "Restaurant reviews"; // contributions screen
const MY_CONTRIBUTIONS = "My Contributions"; // contributions screen
const FOOD_SNAP_NOT_APPROVED = "FoodSnap not approved"; // contributions screen
const I_CANT_SEE_MY_FOOD = "I can't see my FoodSnap"; // contributions screen
const AMAZING = "Amazing"; // RestaurantsReview screen
const IT_WAS_AMAZING_ATMOSPHERE = // RestaurantsReview
    "It was amazing athmosphere, food, with social distancing in place. Defenitely will visit again!";
const GIFT_VALUE = "Gift Value"; //  AllCorporateCards screen
const QUANTITY = "Quantity"; //  AllCorporateCards screen
const RECIPIENTS = "Recipient(s)"; //  AllCorporateCards screen
const NAMES = "Name(s)"; //  AllCorporateCards screen
const JOHN_PETER = "John; Peter"; //  AllCorporateCards screen
const EMAILS = "Email(s)"; //  AllCorporateCards screen
const JOHN_PETER_EMAILS = "johnsmith@yahoo.com; peter21@yahoo.com"; //  AllCorporateCards screen
const MESSAGE = "Message"; //  AllCorporateCards screen
const MESSAGE_HINT_TEXT = """(sent individually) 
Hi [Name per above],
This is a gift from me. Bon appetit. 
Thanks, 
Elizabeth"""; //  AllCorporateCards screen
const DATE_TO_SEND = "Date to send"; //  AllCorporateCards screen
const ELIGIBLE_TIMES = "Eligible times";
const EXPIRY_DATE = "Expiry date";
const ALL = "ALL"; // corporate card screen
const CELEBRATIONS = "Celebration"; // corporate card screen
const GIFT = "Gift"; // corporate card screen
const CORPORATE = "Corporate"; // corporate card screen
const FESTIVITIES = "Festivities"; // corporate card screen
const FOOD_DAYS = "Food days"; // corporate card screen
const GENERAL = "General"; // corporate card screen
const ORDER_THIS_DISHES = "Order this dish"; // dishes screen
const MY_FAVOURITES = "My Favourites"; // my favourites screen
const VALID_UNTIL = "Valid until"; // Exclusive my rewards screen
const RESTAURANTS_LE_PARIS = "Restaurant Le Paris"; // Exclusive my rewards screen
const VALID_ON = "Valid on"; // Exclusive my rewards screen
const NOT_VALID_WITH_ANY_OTHER = "Not valid with any other promotions."; // Exclusive my rewards screen
const VIEW_RESTAURANTS = "View Restaurant"; // Exclusive my rewards screen
const MAKE_A_RESERVATION = "Make a reservation"; // Exclusive my rewards screen
const VIEW_MENU_ORDER = "View Menu & Order"; // Exclusive my rewards screen
const EXCLUSIVE_FOR_SNAP_CONNOISSEURS = "Exclusive for SnapConnoisseurs"; // Exclusive my rewards screen
const REWARD_CREDITS = "Reward Credits"; // MyRewards screen
const NFT_COINS = "NFT Coins"; // MyRewards screen
const EXCLUSIVE_OFFERS = "Exclusive Offers"; // MyRewards screen
const EXCLUSIVE_INVITES = "Exclusive Invites"; // MyRewards screen
const MY_REWARDS = "My rewards"; // MyRewards screen
const UNLOCK_THIS_REWARDS = "Unlock this reward at"; // MyRewards screen
const MY_DETAILS = "My Details"; // MyDetails screen
const CHANGE_DISPLAY_NAME = "Change display name"; // MyDetails screen
const VERIFIED = "verified"; // MyDetails screen
const EMAIL = "Email"; // MyDetails screen
const VERIFY_NOW = "verifiy now"; // MyDetails screen
const ENTER_YOUR_USERNAME = "Enter your username"; // MyDetails screen
const ARE_YOU_FOOD_BLOGGER = "Are you a food blogger?"; // MyDetails screen
const SAVE_CHANGES = "Save changes"; // MyDetails screen
const ELIZABATH_EMAIL = "elizabeth.simpsons@yahoo.com"; // MyDetails screen
const UN_VERIFY = "un verify"; // MyDetails screen
const VERIFY_EMAIL = "Verify email"; // MyDetails screen
const NAME = "Name"; // MyDetails screen
const HINT = "79579 67 256"; // MyDetails screen
const ELIZABATH = "Elizabeth"; // MyDetails screen
const ELIZABATH_SIMPOSANS = "Elizabeth Simpsons"; // MyDetails screen
const VERIFY_MOBILE_NUMBER = "Verify Mobile number"; // MyDetails screen
const PHOTO_CREDIT = "Photo credit:"; // MyDetails screen
const FOOD_BLOGGER = "@foodblogger"; // MyDetails screen
const EXAMPLE_SHOW_ON_PICTURE = "Example (shown on the picture):"; // MyDetails screen
const FOOD_BLOGGER_CONTANTS = // MyDetails screen
    "When you upload a FoodSnap, instead of your first name, we can show your instagram ID as the contributor.  Once your photo has been approved and live on the restaurant’s menu, it will be visible by all SnapEaters. Thus generating traffic to your instagram, especially useful for food/lifestyle bloggers. However, if you wish to remain private, leave this blank. And don’t worry, we will still credit your photo with your first name, profile picture and SnapEat status badge.";
const PROFILE = "Profile"; // my profile  main page screen
const MY_FOOD_PREFERENCES = "My Food preferences"; // my profile  main page screen
const WALLET = "Wallet"; // my profile  main page screen
const SAVED_ADDRESS = "Saved addresses"; // my profile  main page screen
const LOG_OUT = "Log out"; // my profile  main page screen
const RETURN_TO_ORDER = "Return to order"; // my profile  main page screen
const ADD_NEW_ADDRESS = "Add new address"; // saved address screen
const ADD_PAYMENT_METHOD = "Add payment method"; // wallet screen
const YOUR_PAYMENT_INFORMATION_IS_STORED = // wallet screen
    "Your payment information is stored securely";
const MESSAGES = "Messages"; // message screen
const SEARCH_MESSAGES = "Search Messages"; // message screen
const ORDER_DONT_HAVE_ARRIEVED = "Order didn’t arrived"; // message screen
const INAMO_SOHO = "Inamo Soho"; // message screen
const PROMOTIONS = "Promotions"; // Promotions screen
const ENTER_CODE = "Enter code"; // Promotions screen
const ENTER_PROMO_CODE = "Enter promo code"; // Promotions screen
const NEXT_ORDER_10_OFF = "10% OFF your next order"; // Promotions screen
const ALL_RESTAURANTS_HOMECHIEFS = "All Restaurants & HomeChefs"; // Promotions screen
const SERVICE = "Service"; // Promotions screen
const ORDER = "Order"; // Promotions screen
const EARNED_BY_YOUSSOUF = "Earned by inviting Youssouf"; // Promotions screen
const All_CUISINE = "All cuisines"; //serach data screen
const CHANGE = "Change"; // container widgets
const REWARDS = "Rewards"; // HowToEarnRewardsDialogBox screen
const NFT_CREDIT = "NFT Credits"; // HowToEarnRewardsDialogBox screen
const EXCLUSIVE_OFFERS_SNAPEAT = "Exclusive Offers @SnapEpicure level"; // HowToEarnRewardsDialogBox screen
const EXCLUSIVE_INVITE_SNAPEAT = "Exclusive Invites @SnapConnoisseur level"; // HowToEarnRewardsDialogBox screen
const EARN_NFT_CREDITS = "Earn NFT credits with each order, redeem and purchase NFTs."; // HowToEarnRewardsDialogBox screen
const EARN_CREDIT_WITH_EACH_ORDER = "Earn £ credits with each order/review & save on future orders."; // HowToEarnRewardsDialogBox screen
const GET_EXLCUSIVE_DISCOUNTS = "Get exclusive VIP discounts"; // HowToEarnRewardsDialogBox screen
const GET_RESTAURANT_INVITES = "Get restaurant invites, meals are on the house"; // HowToEarnRewardsDialogBox screen
const POINTS = "Points"; // HowToEarnRewardsDialogBox screen
const RESTAURANT_REVIEW_50POINTS = "Restaurant review - 50 points"; // HowToEarnRewardsDialogBox screen
const MEAL_REVIEW_100POINTS = "Meal review - 100 points"; // HowToEarnRewardsDialogBox screen
const FOODSNAP_APPROVED_UPLOAD = "FoodSnap approved upload - 200 points"; // HowToEarnRewardsDialogBox screen
const FRIEND_1_SIGNUP_ORDER = "1 Friend signed up & order - 20 points"; // HowToEarnRewardsDialogBox screen
const FRIEND_5_SIGNUP_ORDER = "5 Friends signed up & order - 1000 points"; // HowToEarnRewardsDialogBox screen
const FRIEND_10_SIGNUP_ORDER = "10 Friends signed up & order - 2000 points"; // HowToEarnRewardsDialogBox screen
const AWARDS = "Awards"; // HowToEarnRewardsDialogBox screen
const TOP_50_SNAPEATRS_THE_MONTH = "£50 for top SnapEaters of the month"; // HowToEarnRewardsDialogBox screen
const CREDIT = "CREDITS"; // RewardsCredit screen
const REDEEM_NOW = "Redeem now"; // RewardsCredit screen
const TRANSACTIONS = "Transactions"; // RewardsCredit screen
const TRANSACTION_65 = "65 transactions"; // RewardsCredit screen
const REASON = "Reason"; // RewardsCredit screen
const REVIEW = "Review"; // RewardsCredit screen
const DATE = "Date"; // RewardsCredit screen
const TIME = "Time"; // RewardsCredit screen
const ORDER_ = "Order#"; // RewardsCredit screen
const REDEMPTION = "Redemption"; // RewardsCredit screen
const ENTER_YOUR_SECURE_EMAIL = "Enter your secure email address."; // RewardsCredit screen
const EMAIL_ADDRESS = "Email address"; // RewardsCredit screen
const ENTER_HERE = "Enter here"; // RewardsCredit screen
const SENT_SECURITY_CODE_TO_EMAIL = "We sent a security code to your email."; // RewardsCredit screen
const SECURITY_CODE = "Security code"; // RewardsCredit screen
const WE_WILL_SEND_GIFT_CODE_VIA = "We will send you a gift card* via"; // RewardsCredit screen
const REDEEM_YOUR_GIFT_CARD_VIA = "Redeem your gift card via"; // RewardsCredit screen
const BROUSE_AND_PURCHASE = "Browse and purchase unique NFTs on the"; // RewardsCredit screen
const NFT_MARKETPLACE = "NFT marketplace."; // RewardsCredit screen
const WOHOOO_INNOVATION_ON_WAY = 'Wohoo! Innovation is on its way.'; // RewardsCredit screen
const YOU_WILL_RECEIVE_YOUR_GIFT_CART_EMAIL = // RewardsCredit screen
    "You will receive your gift card email from within 48 hours.";
const RESEND_CODE = "Resend code";
const RESEND_CODE_ERROR_MESSAGE = "Please check the code sent to your number";
const INCOMPLETE_NUMBER = "Enter a valid number";
